version: '3.8'

services:
  backend:
    build: ./back
    container_name: nfc-backend
    ports:
      - "8443:8443"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped

  frontend:
    build: ./web/dashboard
    container_name: nfc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: nfc-network